//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryWebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibraryWeb.
        /// </summary>
        public static string aplicationName {
            get {
                return ResourceManager.GetString("aplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string bookButton {
            get {
                return ResourceManager.GetString("bookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book status.
        /// </summary>
        public static string bookTableBookStatus {
            get {
                return ResourceManager.GetString("bookTableBookStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string borrowTableAuthor {
            get {
                return ResourceManager.GetString("borrowTableAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book type.
        /// </summary>
        public static string borrowTableBookType {
            get {
                return ResourceManager.GetString("borrowTableBookType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string borrowTableDetails {
            get {
                return ResourceManager.GetString("borrowTableDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount applied.
        /// </summary>
        public static string borrowTableDiscountApplied {
            get {
                return ResourceManager.GetString("borrowTableDiscountApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string borrowTablePrice {
            get {
                return ResourceManager.GetString("borrowTablePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication date.
        /// </summary>
        public static string borrowTablePublicationDate {
            get {
                return ResourceManager.GetString("borrowTablePublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string borrowTableTitle {
            get {
                return ResourceManager.GetString("borrowTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string loginButton {
            get {
                return ResourceManager.GetString("loginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string loginPlaceholder {
            get {
                return ResourceManager.GetString("loginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed list.
        /// </summary>
        public static string naviBorrowedList {
            get {
                return ResourceManager.GetString("naviBorrowedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string naviLogout {
            get {
                return ResourceManager.GetString("naviLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string naviProfile {
            get {
                return ResourceManager.GetString("naviProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search book.
        /// </summary>
        public static string naviSearchBook {
            get {
                return ResourceManager.GetString("naviSearchBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of books.
        /// </summary>
        public static string pageTitleBookSearching {
            get {
                return ResourceManager.GetString("pageTitleBookSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed book list.
        /// </summary>
        public static string pageTitleBorrowedBookList {
            get {
                return ResourceManager.GetString("pageTitleBorrowedBookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string pageTitleLogin {
            get {
                return ResourceManager.GetString("pageTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string passwordPlaceholder {
            get {
                return ResourceManager.GetString("passwordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string rentButton {
            get {
                return ResourceManager.GetString("rentButton", resourceCulture);
            }
        }
    }
}
